<?php
session_start();
if(strlen($_SESSION['login'])==0)
  {
header('location:http://localhost/Apartment_Management_System/');
}
function emailtender($sub,$matter,$id)
{

  require '../libphp-phpmailer/class.phpmailer.php';
  require '../libphp-phpmailer/class.smtp.php';
  $mail = new PHPMailer;
  $mail->setFrom('admin@example.com');
  $mail->addAddress($id);
  $mail->Subject = "$sub";
  $mail->Body = "<h2>Hello!</h2><p>
  ".$matter."</p>";

  $mail->isHTML(true);
  $mail->AltBody = "This message is generated by plain text !";
  $mail->IsSMTP();
  $mail->SMTPSecure = 'ssl';
  $mail->Host = 'ssl://smtp.gmail.com';
  $mail->SMTPAuth = true;
  $mail->Port = 465;

  //Set your existing gmail address as user name
  $mail->Username = 'ams605044@gmail.com';

  //Set the password of your gmail address here
  $mail->Password = 'Admin11123';
  if(!$mail->send()) {
    echo !extension_loaded('openssl')?"Not Available":"Available";
    echo 'Email is not sent.';
    echo 'Email error: ' . $mail->ErrorInfo;
  }
}
include("includes/config.php");
$id=$_GET['complainid'];
$ret=mysqli_query($con,"Update complaint set status='Closed' WHERE complaintid='$id'");
$rat=mysqli_query($con,"SELECT * FROM complaint WHERE complaintid='$id'");
$row = mysqli_fetch_array($rat);
$tid=$row['Techid'];
$drop=1;
$rit=mysqli_query($con,"Update technician set Noofjobs=Noofjobs-'".$drop."' WHERE Techid='$tid'");
$uid=$row['Userid'];
$rit=mysqli_query($con,"SELECT * FROM user WHERE Userid='$uid'");
$rim=mysqli_fetch_array($rit);
$riw=mysqli_query($con,"SELECT * FROM technician WHERE Techid='$tid'");
$riq=mysqli_fetch_array($riw);
$email=$rim['userEmail'];
$name=$rim['firstName'];
$nc=$row['noc'];
$tname=$riq['firstName'];
$tphno=$riq['contactNo'];
$temail=$riq['userEmail'];
$body="Dear $name,<br/><br/> Your Complaint regarding $nc is Solved.<br/><br/>Complaint is Closed.If issue is still not resolved contact alloted technician<br/><br/> Technician : $tname <br/> Contact No: $tphno<br/> Email: $temail";
$sub="Your Complaint $id Closed ";
emailtender($sub,$body,$email);
header('location:http://localhost/Apartment_Management_System/technician/assignedcomplaints.php');
 ?>
