<?php
session_start();
include("includes/config.php");
require '../libphp-phpmailer/class.phpmailer.php';
require '../libphp-phpmailer/class.smtp.php';
function emailtender($sub,$matter,$id)
{


  $mail = new PHPMailer;
  $mail->setFrom('admin@example.com');
  $mail->addAddress($id);
  $mail->Subject = "$sub";
  $mail->Body = "<h2>Hello!</h2><p>
  ".$matter."</p>";

  $mail->isHTML(true);
  $mail->AltBody = "This message is generated by plain text !";
  $mail->IsSMTP();
  $mail->SMTPSecure = 'ssl';
  $mail->Host = 'ssl://smtp.gmail.com';
  $mail->SMTPAuth = true;
  $mail->Port = 465;

  //Set your existing gmail address as user name
  $mail->Username = 'ams605044@gmail.com';

  //Set the password of your gmail address here
  $mail->Password = 'Admin11123';
  if(!$mail->send()) {
    echo !extension_loaded('openssl')?"Not Available":"Available";
    echo 'Email is not sent.';
    echo 'Email error: ' . $mail->ErrorInfo;
  }
}
if(strlen($_SESSION['login'])==0)
  {
header('location:http://localhost/Apartment_Management_System/');
}
$id=$_GET['cid'];
$rda=mysqli_query($con,"SELECT Userid FROM complaint WHERE complaintid='$id'");
  $rdw = mysqli_fetch_array($rda);
  $uid=$rdw['Userid'];
$rdm=mysqli_query($con,"SELECT * FROM user WHERE Userid='$uid'");
$rdn = mysqli_fetch_array($rdm);
$email=$rdn['userEmail'];
$name=$rdn['firstName'];

$del=mysqli_query($con,"DELETE FROM complaint WHERE complaintid='$id'");
$sub="Rejection of Complaint id: $id";
$matter ="Dear $name,<br/><br/> We are Sorry to inform you that the type of service is not available<br/><br/> Thanks for Reaching Us.";
emailtender($sub,$matter,$email);
header('location:http://localhost/Apartment_Management_System/admin/notprocessed.php');

 ?>
