<?php
session_start();

include("includes/config.php");

if(strlen($_SESSION['login'])==0)
  {
header('location:http://localhost/Apartment_Management_System/');
}
$id=$_GET['regid'];
  $ret=mysqli_query($con,"SELECT * FROM Registrationlog WHERE Regid='$id'");
  $row = mysqli_fetch_array($ret);
$firstname=$row['firstName'];
$lastname=$row['LastName'];
$email=$row['userEmail'];
$password=$row['password'];
$contact=$row['contactNo'];
$block=$row['Block'];
$flatno=$row['flatno'];
$status=1;
$insuser=mysqli_query($con,"INSERT INTO user (firstName,lastname,userEmail,password,contactNo,block,flatNumber,status) VALUES ('$firstname','$lastname','$email','$password','$contact','$block','$flatno','$status')");
$outuser=mysqli_query($con,"DELETE FROM Registrationlog WHERE Regid='$id'");
$matter="Registration Accepted <br/> Your userlogin is $email <br/> If you forget your password please click on forget password to generate new password";
$sub="Registration Accepted";
require '../libphp-phpmailer/class.phpmailer.php';
require '../libphp-phpmailer/class.smtp.php';
$mail = new PHPMailer;
$mail->setFrom('admin@example.com');
$mail->addAddress($email);
$mail->Subject = "$sub";
$mail->Body = "<h2>Hello!</h2><p>
".$matter."</p>";

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;

//Set your existing gmail address as user name
$mail->Username = 'ams605044@gmail.com';

//Set the password of your gmail address here
$mail->Password = 'Admin11123';
if(!$mail->send()) {
  echo !extension_loaded('openssl')?"Not Available":"Available";
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
}
header("location:http://localhost/Apartment_Management_System/admin/registerlog.php");
 ?>
